version: '3'

tasks:
  clean:
    cmd: rm -rf dotload_*.deb dotload_*.snap dotload_*.build dotload_*.buildinfo dotload_*.changes dotload_*.dsc dotload_*.tar.xz

  install:
    cmd: ./install.sh

  uninstall:
    cmd: sudo rm "${PREFIX}/bin/dotload"

  build-deb:
    cmds:
      - |
        cd dotload
        if [[ "{{.WORKFLOW}}" = "true" ]]; then
          export DEBEMAIL="{{.EMAIL}}"
          export DEBFULLNAME="{{.FULLNAME}}"
          dch --create --distribution noble --package dotload --newversion "{{.VERSION}}" "{{.CHANGES}}"
          debuild --no-lintian -i -p"gpg --passphrase {{.PASSPHRASE}} --pinentry-mode loopback" -k{{.KEY}}
          debuild --no-lintian -S -sa -p"gpg --passphrase {{.PASSPHRASE}} --pinentry-mode loopback" -k{{.KEY}}
        else
          debuild --no-lintian -us -uc
        fi

  build-snap:
    cmds:
      - |
        # Create version in snapcraft.yaml
        sed -i "s/@@VERSION@@/{{.VERSION}}/g" snap/snapcraft.yaml

        if [[ "{{.WORKFLOW}}" = "true" ]]; then
          sg lxd -c 'snap run snapcraft clean'
          sg lxd -c 'snap run snapcraft --verbose'
        else
          snapcraft clean
          snapcraft --verbose
        fi

        sed -i "s/{{.VERSION}}/@@VERSION@@/g" snap/snapcraft.yaml
