name: dotload
base: core22
version: '1.0.1'
summary: A tool to install dotfiles and other necessary tools
description: |
  This tool helps to quickly install configuration files (dotfiles) and other
  necessary tools from the "dotfiles" repository from the user's GitHub

grade: devel
confinement: devmode

parts:
  dotload:
    # source: https://github.com/okineadev/dotload/releases/download/v1.0.1/dotload_1.0.1.tar.xz
    source: dotload_1.0.1.tar.xz
    plugin: dump

apps:
  dotload:
    command: bin/dotload
