name: dotload
base: core22

summary: This is a tool for installing dotfiles and other tools on any machine
description: |
  `dotload` works by cloning the specified user's **GitHub** dotfiles repository

  This tool was created to make it as **easy as possible** to install dotfiles, required development tools (such as **nodejs**, **php**, **etc**.) and other packages.

title: dotload
contact: https://t.me/okinea
donation: https://github.com/okineadev/dotload?tab=readme-ov-file#%EF%B8%8F-support
source-code: https://github.com/okineadev/dotload
license: MIT

grade: stable
confinement: strict
adopt-info: dotload

architectures:
  - build-on: amd64
    build-for: all

# TODO: idk. what is this...
lint:
  ignore:
    - library:
        - lib/i386-linux-gnu/**
        - usr/lib/i386-linux-gnu/**
        - lib32/**
        - usr/lib32/**

parts:
  dotload:
    # TODO: fix this crutch
    source: dotload_@@VERSION@@.tar.xz
    plugin: dump
    override-pull: |
      craftctl default
      version="$(git describe --tags --abbrev=0 | sed 's/v//g')"
      craftctl set version="$version"
    stage-packages:
      - git

plugs:
  personal-files:
    # TODO: Consider the expediency of the rights
    read:
      - $HOME/.gitconfig
      - $HOME/dotfiles
    write:
      - $HOME/.dotload
      - $HOME/dotfiles
  home:
    interface: home
  network:
    interface: network

apps:
  dotload:
    command: bin/dotload
    environment:
      # TODO: Remove unnecessary values
      LD_LIBRARY_PATH: '$LD_LIBRARY_PATH:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/openssl-1.0.0/engines:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/sasl2'

layout:
  /usr/lib/git-core:
    symlink: $SNAP/usr/lib/git-core
  /usr/share/git-core:
    symlink: $SNAP/usr/share/git-core
